### ISSUE TITLE
Building shared libraries

### ISSUE THREAD

**Issue by nibrahim** [nibrahim/cpslib#20]
It would be nice to be able to build a `.so` with a single `make shared` or something similar.

**Comment by k4rtik** [comment]
Manual steps (for Linux) are ready:
```
k4rtik@DevDebian:~/Projects/cpslib$ gcc -shared -fpic -o libpslib.so pslib_linux.c common.c
k4rtik@DevDebian:~/Projects/cpslib$ gcc -o driver driver.c -L. -lpslib
k4rtik@DevDebian:~/Projects/cpslib$ export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
k4rtik@DevDebian:~/Projects/cpslib$ ./driver | head
 Disk usage
total: 7922466816d
used: 2023047168d
free: 5473386496d
percent: 25.535572

 Physical Disk partitions
Partitions : 1
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered

k4rtik@DevDebian:~/Projects/cpslib$
```

@nibrahim would you like to verify where this suffices for #22? I will have to figure out how to integrate these steps portably into our build system.

**Comment by nibrahim** [comment]
More than enough! Great work. :)

-- 
Cordially,
Noufal
http://nibrahim.net.in

**Comment by k4rtik** [comment]
If you are using these steps, you may also want to include `-Wall -Werror` while building the so.
