### ISSUE TITLE
Unit test each API

### ISSUE THREAD

**Issue by k4rtik** [nibrahim/cpslib#22]
It might be a good idea to set up a test infrastructure such that we could verify compatibility of each API's result with corresponding psutil API's.

Unit testing will also, of course, help prevent future breaking changes.

**Comment by nibrahim** [comment]
I have one or two more APIs to implement for the basic thing. After
that, I'll work on the unit testing. I have some ideas for how to do it
but will need a shared lib target so that I can load it up.

**Comment by k4rtik** [comment]
It's coming soon. :)

**Comment by nibrahim** [comment]
I've got infrastructure for this and some actual tests in the `testing` branch.

**Comment by nibrahim** [comment]
I've merged ths into `master`.
