### ISSUE TITLE
[osx] Get rid of Linux specific fields

### ISSUE THREAD

**Issue by k4rtik** [nibrahim/cpslib#28]
Ref: https://github.com/nibrahim/cpslib/commit/bdeafd87e5f9c5a849778e68cd3668a72c8add2f

1. Need to get rid of Linux specific fields in APIs.
1. Writer platform aware tests, so that they don't need to be changed for each platform.

**Comment by nibrahim** [comment]
1. Linux specific fields...  I don't think we should do common denominator stuff. All available data should be exposed. 
1. I think we can write platform specific tests using py.test skipif http://pytest.org/2.2.4/skipping.html#skipif

**Comment by k4rtik** [comment]
Done with 7ec0accedc5656835c86179e74ed58e171967802
